question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in have more than 7 times", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
]

trivia_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Great Whites sometimes perform the bump-and-bite attack (a test bite) on victims.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "An average human can go two weeks without water.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "The Sun is considered a star.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "A plant that has a life cycle for more than a year is known as an annual.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "The shape of the Earth is a perfect sphere.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Upwelling in the ocean provides colder nutrient rich water for plants and decomposers.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "An atom contains a nucleus.", "correct_answer": "True", "incorrect_answers": ["False"]}]
